### ISSUE TITLE
Minor notes

### ISSUE THREAD

**Issue by dupreezd** [meganrogge/crawler-1#1]
Wow, I love it! The background music makes it feel really epic/exciting to play. I love the breadth of customization options available to the player and the multiple gameplay modes. So much attention to detail. I remember this from class and its really my favorite one so far.

Anyway, here are just a couple things I encountered:
* The next panel moves to the bottom of the window when Chrome is on standard zoom level on my 13 in Macbook. It moved to the right side as intended when I zoomed out to 75%. I would suggest changing the way screen size decreases are handled so that the elements are fixed (or at least tolerate a smaller screen size than it does now).
* The dictation lags if you move through the options too quickly. If possible, you could stop the dictation of the previous option when the user presses "next" again.
* This is very minor but disabling sound effects also disables the background music and dictation whether thats selected or not. I can imagine a user might want the dictation but no music or sound effects, so might be worth adding an extra button.

Overall, I loved it!

**Comment by meganrogge** [comment]
Hey! Thanks for the thoughtful feedback. 

I have incorporated your great ideas (point 1 and 3).

Since the target audience will be unlikely to move through the options very quickly, the second point is not something that worries me at this time.
